name: deep-chroma-ctc

channels:
    - defaults
    - conda-forge

dependencies:
  - python=3.6.*
  - numpy=1.16.*
  - scipy=1.3.*
  - matplotlib=2.0.*
  - ipython=7.7.*
  - jupyter=1.0.*
  - tqdm=4.36.*
  - numba==0.48.*
  - pip:
    - librosa==0.7.*
    - tensorflow==2.*.*
